(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; My custom package
(depends-on "zenburn-theme")
(depends-on "edn")
(depends-on "inflections")
(depends-on "hydra")
(depends-on "paredit")

;; From site-lisp
(depends-on "ace-jump-mode")
(depends-on "annoying-arrows-mode")
(depends-on "bash-completion")
(depends-on "browse-kil-ring")
(depends-on "buster-mode")
(depends-on "buster-snippets")
(depends-on "change-inner")
(depends-on "clj-refactor")
